Repository MicrosoftDocs/azure-dev-docs, pull requests merged in 2022-06, with the labels that each got.

#794 Incorrect link github-key-vault.md
  articles/github/github-key-vault.md
Labels: aq-pr-triaged, github, Change sent to author

#810 Update OTel agent documentation - no package is needed
  articles/java/sdk/tracing.md
Labels: aq-pr-triaged

#814 Typo "Set up a GitHub Actions"→"Use GitHub Actions"
  articles/github/deploy-to-azure.md
Labels: aq-pr-triaged, Change sent to author
