Repository MicrosoftDocs/azure-dev-docs, pull requests merged in 2022-08, with the labels that each got.

#854 Fixed typos in list of key Azure services
  articles/intro/azure-developer-key-services.md
Labels: aq-pr-triaged, Change sent to author

#855 Typo "GitHub Action"→"GitHub Actions"
  articles/javascript/how-to/with-web-app/static-web-app-with-swa-cli/create-static-web-app.md
Labels: aq-pr-triaged, Change sent to author

#864 Wrong version of GH CLI in prerequisites
  articles/azure-developer-cli/includes/azd-install.md
Labels: aq-pr-triaged, azure-dev-cli

#873 Use `bicep` language for `.bicep` code samples
  articles/azure-developer-cli/make-azd-compatible.md
Labels: aq-pr-triaged
